// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tokczzohleqrqqmrllub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRva2N6em9obGVxcnFxbXJsbHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTg1NzYsImV4cCI6MjA2ODY3NDU3Nn0.DIbywM6cCWoDYBt5DNyn3DJO8CvmlrYigGu0-LbccNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});